### ISSUE TITLE
add params to pending state

### ISSUE THREAD

**Issue by futurist** [rolandjitsu/react-fetch-streams#2]
A `Pending state` should be added since the `fetch` should not be called but  pending due to some condition, like the url/params still not ready, after that, the `fetch` can be performed.

That is, add the ability to conditional `fetch`.

**Comment by rolandjitsu** [comment]
@futurist I'm not sure I follow what the request is here. Can you provide an example of what you're trying to achieve?

**Comment by futurist** [comment]
@rolandjitsu Please consider below example:

```js
const [url, setUrl] = useState()
useEffect(()=>{
    if(someDataAndCondition.shouldFetch) {
        setUrl(`http://xxxx/${someDataAndCondition.path}`)
    }
}, [someDataAndCondition, setUrl])

// at first loop, url will be undefined!
useStream(url)
```

Above example useStream should be in `pending` state until `someDataAndCondition.shouldFetch` become to `true` and prepare for the `url`, event when `url` is ready later, the user want to close the request and won't call the url again.

**Comment by rolandjitsu** [comment]
@futurist this can be handled on the user side by using rxjs's merge operators.

**Comment by rolandjitsu** [comment]
Sorry @futurist. My bad. I confused this lib with another one. Still, I think the users can handle that on their side so we can keep the lib simple.

**Comment by rolandjitsu** [comment]
Closing this as the requested feature can be achieved on the user side and the lib should be kept simple.
